### ISSUE TITLE
Links Page

### ISSUE THREAD

**Issue by harrychow04** [HazimAr/School-Simplified#69] opened 2021-08-03 02:08 UTC
<img width="447" alt="Screen Shot 2021-08-02 at 10 06 38 PM" src="https://user-images.githubusercontent.com/74485562/127946297-4f20206f-e4de-4e4d-83fa-4a761ebaf89e.png">

Remove all of the social media links at the bottom and add a "Become a Partner" option below "Contact Us" 

<img width="395" alt="Screen Shot 2021-08-02 at 10 07 01 PM" src="https://user-images.githubusercontent.com/74485562/127946317-7faaccac-30ba-4e20-b115-49b4f99c449a.png">

But aside from this is there anyway to make this linked to like notion or something so we can regularly update links because there are a lot more links than this and there is also a lot of application links that are for specific positions and only last like a week

**Comment by LeftistTachyon** [comment] 2021-08-03 04:56
Duplicate of #62.

Don't be afraid to comment on another person's Issue post :)

**Closed by LeftistTachyon** 2021-08-03 04:56 UTC
Labels: duplicate
